import { Brand } from "@/types/brand";

const brandData: Brand[] = [
  {
    id: 0.1,
    name: "Make",
    href: "https://www.make.com/",
    image: "/images/brand/make2.svg",
    imageLight: "/images/brand/make2.svg",
  },
  {
    id: 0.2,
    name: "OpenAI",
    href: "https://openai.com/",
    image: "/images/brand/openai1.svg",
    imageLight: "/images/brand/openai1.svg",
  },
  {
    id: 0.3,
    name: "React",
    href: "https://nextjs.org/",
    image: "/images/brand/reactjs.svg",
    imageLight: "/images/brand/reactjs.svg",
  },
  {
    id: 0.4,
    name: "Zapier",
    href: "https://zapier.com/",
    image: "/images/brand/zapier.svg",
    imageLight: "/images/brand/zapier.svg",
  },
  {
    id: 0.5,
    name: "Botpress",
    href: "https://botpress.com/",
    image: "/images/brand/botpress.svg",
    imageLight: "/images/brand/botpress.svg",
  },
  {
    id: 0.6,
    name: "Google AI",
    href: "https://ai.google/",
    image: "/images/brand/google.svg",
    imageLight: "/images/brand/google.svg",
  },
  {
    id: 0.7,
    name: "Hugginhface",
    href: "https://huggingface.co/",
    image: "/images/brand/hf.svg",
    imageLight: "/images/brand/hf.svg",
  },
  {
    id: 0.8,
    name: "Adobe",
    href: "https://www.adobe.com/home",
    image: "/images/brand/adobe.svg",
    imageLight: "/images/brand/adobe.svg",
  },
  {
    id: 0.9,
    name: "Python",
    href: "https://www.python.org/",
    image: "/images/brand/python.svg",
    imageLight: "/images/brand/python.svg",
  },
  {
    id: 0.9,
    name: "Javascript",
    href: "https://www.w3schools.com/js/",
    image: "/images/brand/js.svg",
    imageLight: "/images/brand/js.svg",
  },
  {
    id: 1.0,
    name: "Langchain",
    href: "https://www.langchain.com/",
    image: "/images/brand/langchain.svg",
    imageLight: "/images/brand/langchain.svg",
  },
  {
    id: 1.1,
    name: "NextJS",
    href: "https://nextjs.org/",
    image: "/images/brand/nextjs.svg",
    imageLight: "/images/brand/nextjs.svg",
  },
  // {
  //   id: 0.25,
  //   name: "Client",
  //   href: "https://www.facebook.com/profile.php?id=100093134271073",
  //   image: "/images/brand/facebook2.svg",
  //   imageLight: "/images/brand/facebook2.svg",
  // },
  // {
  //   id: 0.3,
  //   name: "Client",
  //   href: "https://twitter.com/piotrmacai",
  //   image: "/images/brand/twitter.svg",
  //   imageLight: "/images/brand/twitter.svg",
  // },
  // {
  //   id: 0.4,
  //   name: "Client",
  //   href: "https://www.linkedin.com/company/aiware-me/",
  //   image: "/images/brand/linkedin.svg",
  //   imageLight: "/images/brand/linkedin.svg",
  // },
  // {
  //   id: 0.5,
  //   name: "Client",
  //   href: "https://www.instagram.com/piotrmacai/",
  //   image: "/images/brand/instagram.svg",
  //   imageLight: "/images/brand/instagram.svg",
  // },
  // {
  //   id: 0.6,
  //   name: "Client",
  //   href: "https://www.youtube.com/channel/UCQCw9Wg1bKWi_j1taARicCA",
  //   image: "/images/brand/youtube.svg",
  //   imageLight: "/images/brand/youtube.svg",
  // },
  // {
  //   id: 0.7,
  //   name: "Client",
  //   href: "https://www.behance.net/piotrmacai/",
  //   image: "/images/brand/behance.svg",
  //   imageLight: "/images/brand/behance.svg",
  // },
];

export default brandData;
